services:
  ethereum-node:
    image: parity/parity:latest
    container_name: my-parity
    command:
        --chain dev
        --jsonrpc-interface all
        --jsonrpc-hosts all
        --ws-interface all
        --ws-origins all
        --ws-hosts all
        --base-path /home/parity/.local/share/io.parity.ethereum/
    volumes:
      - ./data:/home/parity/.local/share/io.parity.ethereum
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303